# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ea299a71c14410d1abbd36de2817576fc3cfd356c4995e6897edb19dd54e3642684252870c68f0d5c46c0d58f517fd63922af5d6f06af68011c5a9076e5d63b

test:
  secret_key_base: 1a9ca91b59f7367a984de4bf30bccb5b9a9deafdb92f5492c8e15366dd4ae47dde551836d03ebcbf17532f0ae5184240eb64a5d81c1cffd429789b15721f67a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
